sourcebots/robot-api

robot/board.py
robot/robot.py

Fixes https://github.com/sourcebots/robot-api/blob/master/robot/robot.py#L53
Allow boards to be indexed by serial number and integer index. Also prevent modification to the boards list

Create BoardList structure

---

robot/board.py
robot/camera.py
robot/game.py
robot/motor.py
robot/servo.py
robot/zone_script.py

I've been developing in python 3.6, the json api doesn't accept bytestrings in python 3.4, this patch is to make the code compatible with 3.4

Python34compatibility

---

robot/camera.py

Fix condition where sometimes the camera would try to get a list of
tokens from the wlcome message, which is b'{}'

Fix camera race condition

---

examples/ideal_api.py
robot/game_specific.py
robot/servo.py
tests/test_servos.py

Reverts sourcebots/robot-api#15

Revert "define TCR marker IDs and Sizes"

---

requirements.txt
requirements_test.txt
robot/__init__.py
robot/board.py
robot/camera.py
robot/game.py
robot/markers.py
robot/motor.py
robot/power.py
robot/robot.py
robot/servo.py
robot/zone_script.py
tests/mock_robotd.py
tests/test_game.py
tests/test_power.py

Currently we use `SOCK_SEQPACKET` to send messages, but we also split up our packets into chunks which reduces the usefulness of this feature. Additionally, `SOCK_SEQPACKET` isn't supported on macOS which makes it problematic to run the tests for certain users.

Use TCP Streams

---

robot/power.py
robot/robot.py
tests/mock_robotd.py

This code blocks the robot initialising until the button has been pressed.

Blocking start

---

robot/power.py

Makes the robot buzz!! :bee::bee::bee::bee::bee::bee:
Linked to https://github.com/sourcebots/robotd/pull/28

Make the robot buzz

---

tests/mock_robotd.py

- Add board mixin for common code
- Add function to clear message queue

Board mixin

---

robot/motor.py
tests/test_motors.py

Rename the motor property `power`, because it's not actually the voltage!
Related to https://github.com/sourcebots/docs/pull/34

Motor property

---

tests/test_camera.py

`camera_tests` were importing `game_specific` from the wrong module, this fixes that

Fix tests importing the wrong game_specific

---

robot/servo.py

I'm not sure what this was used for, but it's unused.

Remove dead Servo._get_status method

---

robot/camera.py
tests/test_camera.py

This adds tests for the vision results and simplifies the code getting them.

Tidy vision results

---

robot/board.py
robot/game.py
robot/motor.py

This fixes the linting issues remaining on the branch, hopefully getting to a point where we can merge #22 and then be in a good state to merge #34.

Tidy serial in base

---

robot/robot.py

Not sure how I missed this in review :man_facepalming:

Replace redundant set comprehension with a call to set()

---

robot/board.py
robot/camera.py
robot/game.py
robot/markers.py
robot/robot.py
setup.cfg

Various small fixes to my own review comments on #34.

Type checking tweaks

---

tests/test_power.py

Fix "Initialization Updates"

---

robot/markers.py
tests/test_camera.py
tests/test_markers.py

This exposes the new "spherical" coordinates from https://github.com/sourcebots/sb-vision/pull/23.

Clarify coordinates

---

robot/power.py
robot/robot.py

To allow teams to choose when they wait for the start button to be pressed

Allow teams to decide when to wait for start button

---

robot/board.py
robot/robot.py
script/linting/requirements.txt
tests/mock_robotd.py

This replaces all the print statements in the main code with suitable logging lines. This doesn't actually configure the logging yet, though we should probably do that.

Move to logging

---

robot/robot.py

I jumped the gun a bit in #73 and didn't actually include any logging configuration before merging... oops.

Actually configure logging

---

robot/game_specific.py

*Do Not Merge* until https://github.com/sourcebots/sb-vision/pull/33 is
merged

update game_specific.py to match sb-vision

---

robot/markers.py

Improve the docstrings for polar co-ordinates

---

robot/__init__.py
robot/robot.py
setup.py

Print the version number when we start.
It grabs the version number from setup.py

Add version number log message

---

robot/servo.py

Update pin modes to match https://github.com/sourcebots/servo-firmware/blob/rewrite/src/firmware.cpp#L193

Update pin mode enum values

---

robot/servo.py

Update type signature to match https://github.com/sourcebots/robotd/pull/47

Return analogue values as float rather than strings

---

robot/board.py
robot/camera.py
robot/power.py
robot/robot.py

Fixes lint issues shown up by more recent linter versions.

Lint fixes
